### ISSUE TITLE
WIFI not working 

### ISSUE THREAD

**Issue by veerpawan** [technexion-android/manifest#4]
Successfully place the WiFi and Bluetooth drivers get from the sales team of TechNexion. Again build the OS but the only Bluetooth is working WiFi not working

**Comment by wigcheng** [comment]
Please provide your 'dmesg' log here  as a txt file, also check output of 'lsmod' command.
Did you see wlan0 when issue ifconfig -a command?

**Comment by veerpawan** [comment]
[wifierror.txt](https://github.com/technexion-android/manifest/files/5849166/wifierror.txt)
 Please have a look on the logcat file and let us know the steps to implement WiFi.

**Comment by wigcheng** [comment]
It seems WiFi driver initial failed, please double check as following items:

1. Do you change source code so much especially init.rc?
2. You forgot provide dmesg log to me (just type dmesg in console and save as txt file to me), please provide it.
3. Make sure your firmware path is correct, provide me the output log when issue "ls /vendor/etc/firmware/"

Thanks

**Comment by veerpawan** [comment]
**Do you change source code so much especially init.rc?**
Didn't touch init.rc


**You forgot provide dmesg log to me (just type dmesg in console and save as txt file to me), please provide it.**



[demsg.txt](https://github.com/technexion-android/manifest/files/5866103/demsg.txt)

**Make sure your firmware path is correct, provide me the output log when issue "ls /vendor/etc/firmware/"**

bdwlan30.bin  imx  otp30.bin  qca  qwlan30.bin  tfa98xx.cnt  utf30.bin  wlan

**Comment by veerpawan** [comment]
Hi WigCheng 
Please have a look at this and provide me steps to enable WiFi. I am unable to use WiFi.

**Comment by wigcheng** [comment]
Please provide your dmesg log from your imx8 board.....
You gave me the dmesg from your host PC, it's useless.

Thanks

**Comment by veerpawan** [comment]
Please find the demsg file.

I also flash the demo image before and WiFi workes fine in demo image.


[demsg.txt](https://github.com/technexion-android/manifest/files/5903736/demsg.txt)

**Comment by wigcheng** [comment]
I don't know why you always send me your host PC dmesg log... 
[Feb 1 14:19] Linux version 4.15.0-29-generic (buildd@lgw01-amd64-057) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 (Ubuntu 4.15.0-29.31-generic 4.15.18)

it's x64 base log, do you know how to get dmesg in your target board??

**Comment by veerpawan** [comment]
**it's x64 base log, do you know how to get dmesg in your target board??**

Please let me know steps to get dmesg log.

**Comment by wigcheng** [comment]
Easiest way:

1. Connect a micro-USB cable between host PC and Wandboard.
2.  issue command 'adb shell' into target board console
3. $ su
4. # dmesg

done

**Comment by veerpawan** [comment]
Steps I followed.

1. Open the terminal from TechNexion root directory.
2. execute command ----------> adb shell
3. execute command ----------> $ su
4. execute command ----------> dmesg
5. copy the terminal code and create as text file.
6. Please find the attahced dmesg file
[demsg.txt](https://github.com/technexion-android/manifest/files/5910346/demsg.txt)

**Comment by wigcheng** [comment]
Make sure you follow the instructions : 
https://github.com/technexion-android/cookers/tree/tn-p9.0.0_2.0.1_8m-ga#enabling-wifibt-function

According your log you made mistake and Wi-Fi driver / firmware did not load.

**Comment by veerpawan** [comment]
[dmesg.txt](https://github.com/technexion-android/manifest/files/5943461/dmesg.txt)
Still not working.

**Comment by mars9820** [comment]
Your logfile is not a complete boot log. Therefore Wig has issues to reply to your request.

Make sure you follow the instructions :
https://github.com/technexion-android/cookers/tree/tn-p9.0.0_2.0.1_8m-ga#enabling-wifibt-function

You most likely put the wireless firmware files in the wrong folder (or didn't insert them at all) PRIOR compiling your image.

Please follow the instructions. They are tested to work without problems. 

If you still have difficulties. Please contact sales@technexion.com with project information and your account manager can discuss how to support you further.
